ejercicio6: ejercicio6.cpp Ortoedro.o
	g++ ejercicio6.cpp Ortoedro.o Coordenada.o -o ejercicio6
Ortoedro.o: Ortoedro.cpp Coordenada.o Ortoedro.h 
	g++ Ortoedro.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h 
	g++ Coordenada.cpp -c